test db production

diff --git a/docker-compose.prod.yml b/docker-compose.prod.yml
--- a/docker-compose.prod.yml
+++ b/docker-compose.prod.yml
@@ -1,4 +1,29 @@
 services:
+  # db:
+  #   image: postgres:16
+  #   volumes:
+  #     - postgres_data:/var/lib/postgresql/data
+  #     - ./backups:/backups
+  #     - ./restore_db.sh:/docker-entrypoint-initdb.d/restore_db.sh
+  #   environment:
+  #     BACKUP_FILE: /backups/aialpha-database-prod-16-10-24.sql
+  #     POSTGRES_DB: ${POSTGRES_DB_PROD}
+  #     POSTGRES_USER: ${POSTGRES_USER_PROD}
+  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_PROD}
+  #   healthcheck:
+  #     test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER_PROD} -d ${POSTGRES_DB_PROD}"]
+  #     interval: 20s
+  #     timeout: 10s
+  #     retries: 3
+  #   ports:
+  #     - "5435:5432"
+  #   networks:
+  #     - myapp_network
+  #   command: >
+  #     bash -c "
+  #       chmod +x /docker-entrypoint-initdb.d/restore_db.sh &&
+  #       docker-entrypoint.sh postgres
+  #     "
   db:
     image: postgres:16
     volumes:
@@ -21,7 +46,14 @@ services:
       - myapp_network
     command: >
       bash -c "
-        chmod +x /docker-entrypoint-initdb.d/restore_db.sh &&
+        set -e
+        echo 'Setting execute permissions for restore_db.sh'
+        chmod +x /docker-entrypoint-initdb.d/restore_db.sh
+        echo 'Contents of /docker-entrypoint-initdb.d:'
+        ls -la /docker-entrypoint-initdb.d/
+        echo 'Executing restore_db.sh'
+        /docker-entrypoint-initdb.d/restore_db.sh
+        echo 'Starting PostgreSQL'
         docker-entrypoint.sh postgres
       "
 
